--- #YAML:1.0
name:                File-Tabular
version:             0.71
abstract:            searching and editing flat tabular files
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    Hash::Type:                    1.0
    Search::QueryParser:           0.92
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Laurent Dami <laurent.dami AT etat ge ch>
