# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Tabular
version:      0.64
version_from: lib/File/Tabular.pm
installdirs:  site
requires:
    Hash::Type:                    1.0
    Search::QueryParser:           0.9

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
